### PR TITLE
Backout rubocop suggestion which causes failures

### LINKED ISSUE #31: Syntax Error in tacacs_server provider
```
veos1#sh version 
Software image version: 4.15.3F
veos1#sh extensions 
Name                                       Version/Release           Status extension
------------------------------------------ ------------------------- ------ ----
puppet-agent-1.3.5-1.eos4.i386.swix        1.3.5/1.eos4              A, I      1
rbeapi-puppet-aio-0.5.1-1.swix             0.5.1/1.eos4              A, I      4

A: available | NA: not available | I: installed | NI: not installed | F: forced
veos1#bash sudo puppet agent --version
4.3.2
```

```
-bash-4.1# puppet describe --list | grep tacacs
Error: Could not autoload puppet/provider/tacacs_server/eos: /opt/puppetlabs/puppet/cache/lib/puppet/provider/tacacs_server/eos.rb:114: syntax error, unexpected tCONSTANT, expecting keyword_do or '{' or '('
...hostname] || fail ArgumentError, 'hostname required'
...                               ^
/opt/puppetlabs/puppet/cache/lib/puppet/provider/tacacs_server/eos.rb:114: dynamic constant assignment
...ostname] || fail ArgumentError, 'hostname required'
...                               ^
/opt/puppetlabs/puppet/cache/lib/puppet/provider/tacacs_server/eos.rb:114: syntax error, unexpected '\n', expecting :: or '[' or '.'
Error: Could not autoload puppet/type/tacacs_server: Could not autoload puppet/provider/tacacs_server/eos: /opt/puppetlabs/puppet/cache/lib/puppet/provider/tacacs_server/eos.rb:114: syntax error, unexpected tCONSTANT, expecting keyword_do or '{' or '('
...hostname] || fail ArgumentError, 'hostname required'
...                               ^
/opt/puppetlabs/puppet/cache/lib/puppet/provider/tacacs_server/eos.rb:114: dynamic constant assignment
...ostname] || fail ArgumentError, 'hostname required'
...                               ^
/opt/puppetlabs/puppet/cache/lib/puppet/provider/tacacs_server/eos.rb:114: syntax error, unexpected '\n', expecting :: or '[' or '.'
Error: Could not run: Could not autoload puppet/type/tacacs_server: Could not autoload puppet/provider/tacacs_server/eos: /opt/puppetlabs/puppet/cache/lib/puppet/provider/tacacs_server/eos.rb:114: syntax error, unexpected tCONSTANT, expecting keyword_do or '{' or '('
...hostname] || fail ArgumentError, 'hostname required'
...                               ^
/opt/puppetlabs/puppet/cache/lib/puppet/provider/tacacs_server/eos.rb:114: dynamic constant assignment
...ostname] || fail ArgumentError, 'hostname required'
...                               ^
/opt/puppetlabs/puppet/cache/lib/puppet/provider/tacacs_server/eos.rb:114: syntax error, unexpected '\n', expecting :: or '[' or '.'
```

### PR DESCRIPTION
**Pull request by jerearista**
Fixes #31

### CODE REVIEW

**Comment by jerearista** [comment]
Added a test manifest and located a number of issues.  There are a couple of outstanding issues in rbeapi (snmp_user) and an issue with netdev network_trunk type (string/integer comparison) to make things whole.

File: lib/puppet/provider/tacacs/eos.rb [hunk 1]
```diff
@@ -26,7 +26,7 @@
   def self.instances
     result = node.api('tacacs').get
     provider_hash = { name: 'settings', ensure: :present }
-    provider_hash[:enable] = result['enable'].to_s.to_sym
+    provider_hash[:enable] = :true
```
Comment (devrobo) [inline lib/puppet/provider/tacacs/eos.rb]: This looks weird. It is always enabled and we don't use any of the values returned from the rbeapi call. Clearly the rbeapi api method has issues because it claims to return a name and an enable value but doesn't appear to do this.

Comment (jerearista) [inline lib/puppet/provider/tacacs/eos.rb]: Agreed, but from the provider's standpoint, it doesn't matter what the API returns for enable as it will always be true.   I can open an issue in rbeapi, too.
